"""Convert a saturn findings doc into a real .ipynb file.

The notebook view is HTML-only — academics open it, look, leave. This module
emits a `nbformat`-compatible JSON document so they can download a notebook,
open it in JupyterLab/VSCode, run the cells, and continue exploring with the
same dataframe in memory.

Output structure:
    1. markdown title + dataset overview
    2. code cell — `pip install` + load the findings JSON
    3. markdown — dataset-scope LLM summary (when present)
    4. markdown — schema dataframe overview
    5. per-column triplet:
       a. markdown heading + LLM column insight
       b. code cell that prints the stats dict (works without re-running saturn)
       c. code cell that draws a matplotlib figure from the embedded extras
    6. markdown — reproducibility footer

Plot code uses matplotlib (academic default). It reads from `findings['columns']`
so the user doesn't need saturn or the original data on hand to inspect the
existing profile — they only need the .json sidecar (also auto-downloaded
beside the .ipynb if you fetch from the viewer's bundled-export endpoint).
"""

from __future__ import annotations

import uuid
from typing import Any

NBFORMAT = 4
NBFORMAT_MINOR = 5


def _new_id() -> str:
    return uuid.uuid4().hex[:8]


def _md(source: str) -> dict[str, Any]:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source.split("\n") if "\n" in source else [source],
    }


def _code(source: str) -> dict[str, Any]:
    return {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": source.split("\n") if "\n" in source else [source],
    }


def _ensure_lines(source: str) -> list[str]:
    """nbformat expects sources as lists of lines (with newlines preserved)."""
    if "\n" not in source:
        return [source]
    parts = source.split("\n")
    return [p + "\n" for p in parts[:-1]] + [parts[-1]]


def _md_lines(source: str) -> dict[str, Any]:
    return {
        "id": _new_id(),
        "cell_type": "markdown",
        "metadata": {},
        "source": _ensure_lines(source),
    }


def _code_lines(source: str) -> dict[str, Any]:
    return {
        "id": _new_id(),
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": _ensure_lines(source),
    }


def _profile_to_ipynb(doc) -> dict[str, Any]:
    raw = doc.raw
    meta = raw.get("meta", {})
    columns = raw.get("columns", [])
    insights = raw.get("insights", {}) or {}
    insight_items = insights.get("insights", []) or []
    by_target = {i.get("target"): i for i in insight_items}
    dataset_insight = by_target.get("__global__")

    cells: list[dict[str, Any]] = []

    # 1. title + overview
    overview = (
        f"# {doc.id.replace('-', ' ').replace('_', ' ')}\n\n"
        f"- **Source:** `{meta.get('source', '?')}`\n"
        f"- **Rows:** {meta.get('row_count', '?'):,}\n"
        f"- **Columns:** {len(columns)}\n"
        f"- **Profiled:** {meta.get('generated_at', '')[:10]}\n"
        f"- **Saturn:** v{raw.get('saturn_version', '?')}\n\n"
        "This notebook was exported from a saturn reading. The deterministic "
        "stats you see here came from saturn's profile pass; the prose summaries "
        "below came from a language model that only saw the per-column aggregates "
        "in the findings JSON."
    )
    cells.append(_md_lines(overview))

    # 2. load findings
    load_code = (
        "# Load the findings sidecar that ships alongside this notebook.\n"
        "import json\n"
        f"findings = json.load(open('{doc.id}.json'))\n"
        "print(f\"{len(findings['columns'])} columns, \"\n"
        "      f\"{findings['meta']['row_count']:,} rows\")"
    )
    cells.append(_code_lines(load_code))

    # 3. dataset summary
    if dataset_insight:
        narrative = dataset_insight.get("narrative", "").strip()
        cells.append(_md_lines(
            f"## Dataset summary\n\n"
            f"> {narrative}\n\n"
            f"*generated by `{dataset_insight.get('model', '?')}`, "
            f"confidence {dataset_insight.get('confidence', '?')}*"
        ))

    # 4. schema overview
    schema_md_rows = ["| column | kind | n | null % | unique |", "| --- | --- | ---: | ---: | ---: |"]
    for c in columns:
        nr = (c.get("null_rate") or 0) * 100
        nu = c.get("n_unique")
        schema_md_rows.append(
            f"| `{c['column']}` | {c.get('kind', '?')} | {c.get('n', 0):,} | "
            f"{nr:.1f}% | {nu:,} |" if nu is not None else
            f"| `{c['column']}` | {c.get('kind', '?')} | {c.get('n', 0):,} | "
            f"{nr:.1f}% | — |"
        )
    cells.append(_md_lines("## Schema\n\n" + "\n".join(schema_md_rows)))

    # 5. per-column cells
    for c in columns:
        ci = by_target.get(c["column"])
        head = f"## `{c['column']}` ({c.get('kind', '?')})"
        if ci:
            head += f"\n\n> {ci.get('narrative', '')}\n\n*{ci.get('model', '?')}, confidence {ci.get('confidence', '?')}*"
        cells.append(_md_lines(head))

        stats_code = (
            "from pprint import pprint\n"
            f"col = next(c for c in findings['columns'] if c['column'] == '{c['column']}')\n"
            "pprint({\n"
            "    'n': col['n'],\n"
            "    'null_rate': col['null_rate'],\n"
            "    'n_unique': col['n_unique'],\n"
            "    **col.get('stats', {}),\n"
            "})"
        )
        cells.append(_code_lines(stats_code))

        plot_code = _plot_for(c)
        if plot_code:
            cells.append(_code_lines(plot_code))

    # 6. reproducibility footer
    footer_lines = [
        "## Reproducibility",
        "",
        f"- saturn v{raw.get('saturn_version', '?')}",
        f"- mode: {meta.get('mode', '?')}",
        f"- seed: {meta.get('seed', '?')}",
        f"- generated: {meta.get('generated_at', '')}",
    ]
    if insights.get("providers"):
        footer_lines += [
            f"- insight models: {', '.join(insights['providers'])}",
            "- prompt version: saturn-insight-v1",
        ]
        usage = insights.get("total_usage", {})
        total_tokens = usage.get("total_tokens", usage.get("input_tokens", 0) + usage.get("output_tokens", 0))
        if total_tokens:
            footer_lines.append(f"- tokens: {total_tokens:,}")
    cells.append(_md_lines("\n".join(footer_lines)))

    return _wrap(cells)


def _compare_to_ipynb(doc) -> dict[str, Any]:
    raw = doc.raw
    insights = raw.get("insights", {}) or {}
    insight_items = insights.get("insights", []) or []
    by_target = {i.get("target"): i for i in insight_items}
    global_insight = by_target.get("__global__")

    cells: list[dict[str, Any]] = []
    cells.append(_md_lines(
        f"# {doc.a_label} vs {doc.b_label}\n\n"
        f"- **{doc.a_label}:** {raw['a'].get('row_count', '?'):,} rows · `{raw['a'].get('source', '?')}`\n"
        f"- **{doc.b_label}:** {raw['b'].get('row_count', '?'):,} rows · `{raw['b'].get('source', '?')}`\n"
        f"- **Columns compared:** {len(raw.get('columns', []))}\n"
        f"- **Generated:** {raw.get('generated_at', '')[:10]}\n"
    ))

    cells.append(_code_lines(
        "import json\n"
        f"compare = json.load(open('{doc.id}.json'))\n"
        "print(len(compare['columns']), 'columns,', len(compare['divergences']), 'divergences')"
    ))

    if global_insight:
        cells.append(_md_lines(
            f"## Compare summary\n\n> {global_insight.get('narrative', '')}\n\n"
            f"*{global_insight.get('model', '?')}, confidence {global_insight.get('confidence', '?')}*"
        ))

    if raw.get("divergences"):
        rows = ["| column | kind | score | signals |", "| --- | --- | ---: | --- |"]
        for d in raw["divergences"]:
            sigs = ", ".join(d.get("signals", []))
            rows.append(f"| `{d['column']}` | {d.get('kind', '?')} | {d.get('score', 0):.2f} | {sigs} |")
        cells.append(_md_lines("## Most divergent columns\n\n" + "\n".join(rows)))

    for c in raw.get("columns", []):
        ci = by_target.get(c["column"])
        head = f"## `{c['column']}` ({c.get('kind', '?')})"
        if ci:
            head += f"\n\n> {ci.get('narrative', '')}\n\n*{ci.get('model', '?')}*"
        cells.append(_md_lines(head))
        cells.append(_code_lines(
            f"col = next(c for c in compare['columns'] if c['column'] == '{c['column']}')\n"
            "from pprint import pprint\n"
            "pprint(col['delta'])"
        ))

    return _wrap(cells)


def _plot_for(col: dict[str, Any]) -> str | None:
    """Emit a matplotlib snippet that draws a plot from `col` (no saturn import)."""
    kind = col.get("kind")
    name = col["column"]
    extras = col.get("extras", {}) or {}

    if kind == "numeric":
        hist = extras.get("histogram") or {}
        if not hist.get("counts"):
            return None
        return (
            "import matplotlib.pyplot as plt\n"
            f"col = next(c for c in findings['columns'] if c['column'] == '{name}')\n"
            "hist = col['extras']['histogram']\n"
            "edges = hist['edges']; counts = hist['counts']\n"
            "centers = [(edges[i] + edges[i+1]) / 2 for i in range(len(counts))]\n"
            "fig, ax = plt.subplots(figsize=(8, 3.5))\n"
            "ax.bar(centers, counts, width=(edges[1]-edges[0]) * 0.9)\n"
            "ax.axvline(col['stats'].get('median', 0), linestyle='--', color='black', label='median')\n"
            f"ax.set_title('{name} distribution')\n"
            f"ax.set_xlabel('{name}')\n"
            "ax.set_ylabel('rows')\n"
            "ax.legend()\n"
            "plt.tight_layout(); plt.show()"
        )

    if kind == "categorical":
        top_values = extras.get("top_values") or []
        if not top_values:
            return None
        return (
            "import matplotlib.pyplot as plt\n"
            f"col = next(c for c in findings['columns'] if c['column'] == '{name}')\n"
            "tv = col['extras']['top_values'][:15]\n"
            "labels = [str(t[0]) for t in tv][::-1]\n"
            "vals = [t[1] for t in tv][::-1]\n"
            "fig, ax = plt.subplots(figsize=(8, max(2.5, 0.3 * len(labels))))\n"
            "ax.barh(labels, vals)\n"
            f"ax.set_title('{name} — top values')\n"
            "ax.set_xlabel('rows')\n"
            "plt.tight_layout(); plt.show()"
        )

    if kind == "text":
        lh = extras.get("length_histogram") or {}
        if not lh.get("counts"):
            return None
        return (
            "import matplotlib.pyplot as plt\n"
            f"col = next(c for c in findings['columns'] if c['column'] == '{name}')\n"
            "lh = col['extras']['length_histogram']\n"
            "edges = lh['edges']; counts = lh['counts']\n"
            "centers = [(edges[i] + edges[i+1]) / 2 for i in range(len(counts))]\n"
            "fig, ax = plt.subplots(figsize=(8, 3.5))\n"
            "ax.bar(centers, counts, width=(edges[1]-edges[0]) * 0.9)\n"
            f"ax.set_title('{name} — character-length distribution')\n"
            "ax.set_xlabel('chars')\n"
            "ax.set_ylabel('rows')\n"
            "plt.tight_layout(); plt.show()"
        )

    return None


def _wrap(cells: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "mimetype": "text/x-python",
                "file_extension": ".py",
            },
        },
        "nbformat": NBFORMAT,
        "nbformat_minor": NBFORMAT_MINOR,
    }


def to_ipynb(doc) -> dict[str, Any]:
    """Public entry: dispatch on profile vs compare findings."""
    from .loader import FindingsKind

    if doc.kind is FindingsKind.PROFILE:
        return _profile_to_ipynb(doc)
    return _compare_to_ipynb(doc)
